services:
  - type: pserv
    name: timeli-db
    plan: free

  - type: web
    name: timeli-web
    env: python
    runtime: python-3.11.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py migrate && python manage.py seed_data && python manage.py collectstatic --noinput
    startCommand: gunicorn timeli.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: timeli-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: timeli.settings