services:
  - type: web
    name: timeli-web
    env: python
    runtime: python-3.11.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py migrate && python manage.py seed_data && python manage.py collectstatic --noinput
    startCommand: gunicorn timeli.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_Pm6pbMRzU5gA@ep-divine-tree-ahu5dja4-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: DJANGO_SETTINGS_MODULE
        value: timeli.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true